test:
	g++ -g -I../ -D_LIB_ -D_TEST_ test.cpp main.cpp ../vm.cpp ../utils.cpp

examples:
	../tools/compiler ../examples/tests/example1
	../tools/compiler ../examples/tests/example2
	../tools/compiler ../examples/tests/example3
	../tools/compiler ../examples/tests/example4
	../tools/compiler ../examples/tests/example5
	../tools/compiler ../examples/tests/example6
